name: CI Workflow

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  sonar-and-unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Sonar Cloud
      run: sonar-scanner

    - name: Run Unit Tests
      run: pytest

  merge-check:
    runs-on: ubuntu-latest

    needs: sonar-and-unit-tests

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check Sonar Pass Percentage
      run: |
        sonar_pass_percentage=$(curl -s 'your_sonar_cloud_project_url/api/measures/component?component=your_project_key&metricKeys=coverage' | jq -r '.component.measures[0].value')
        echo "Sonar Pass Percentage: $sonar_pass_percentage%"
        if [ $(echo "$sonar_pass_percentage >= 40" | bc -l) -ne 1 ]; then
          echo "Sonar coverage is below the required threshold. Merging is not allowed."
          exit 1
